version: '3'
services:
  app: 
    container_name: auction-house
    restart: always
    build: .
    ports:
     - '80:3000'
    links:
     - maria
  maria:
    container_name: maria
    image: mariadb
    volumes:
      - container-volume:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - '4000:4000'
    environment:
      MYSQL_ROOT_PASSWORD: example
volumes:
  container-volume:
